langDef={
	poly:"Polymer",
	sele:"Selected",
	rem:"Remaining",
	supaQ:"Please enter the name of the atom group.",
	multQ:"To define an oligomer, enter the number of repetitions, to define a polymer enter a variable name in lower case letters like \"n\".",
	newButton:"New",
	openButton:"Open",
	saveButton:"Save",
	saveSVGButton:"Save SVG",
	undoButton:"Undo",
	redoButton:"Redo",
	zoomInButton:"Zoom in",
	zoomOutButton:"Zoom out",
	cutButton:"Cut",
	copyButton:"Copy",
	pasteButton:"Paste",
	deleteButton:"Delete",
	helpButton:"Help and keyboard shortcuts",
	infoButton:"Info on Sciformation VectorMol",
	templateShortcuts:"Comma-separated list of shortcuts for the template",
	templateName:"Name of the template",
	selRect:"Rectangular selection tool",
	selLasso:"Freehand selection tool",
	flipH:"Flip horizontal",
	flipV:"Flip vertical",
	del:"Delete selected atoms/bonds",
	rotate:"Rotate selection",
	"3d_rotate":"3D-rotate selection",
	bond_rotate:"Rotate selection around bond",
	newAtomSym:"Atom type or template shortcut",
	atom:"Change atom symbol",
	single:"Single bond",
	"double":"Double bond",
	triple:"Triple bond",
	singleUp:"Bond pointing up",
	singleDown:"Bond pointing down",
	singleEither:"Bond of undefined stereochemistry",
	anyBond:"Unspecified bond",
	aromaticBond:"Aromatic bond",
	drawChain:"Chain tool",
	createGroupButton:"Create group from selection",
	ungroupButton:"Ungroup selected groups",
	clean2D:"Optimize 2D structure",
	clean3D:"Optimize 3D structure",
	setHotspot:"Set hotspot for inserting",
	plusButton:"Separate reaction components using a plus",
	arrowButton:"Reaction arrow"
};