langDef={
	poly:"Polymer",
	sele:"Ausgewählt",
	rem:"Verbleibend",
	supaQ:"Bitte geben Sie einen Namen für die Gruppe an",
	multQ:"Um ein Oligomer zu definieren, geben Sie die Zahl der Wiederholungen an. Für ein Polymer geben Sie eine Variable in Kleinbuchstaben wie \"n\" an.",
	newButton:"Neu",
	openButton:"Öffnen",
	saveButton:"Speichern",
	saveSVGButton:"SVG speichern",
	undoButton:"Rückgängig",
	redoButton:"Wiederherstellen",
	zoomInButton:"Ansicht vergrößern",
	zoomOutButton:"Ansicht verkleinern",
	cutButton:"Ausschneiden",
	copyButton:"Kopieren",
	pasteButton:"Einfügen",
	deleteButton:"Löschen",
	helpButton:"Hilfe und Tastaturbefehle",
	infoButton:"Info über Sciformation VectorMol",
	templateShortcuts:"Kürzel für die Vorlage als kommagetrennte Liste",
	templateName:"Name der Vorlage",
	selRect:"Rechteckauswahl",
	selLasso:"Freihandauswahl",
	flipH:"Linke und rechte Seite vertauschen",
	flipV:"Oberen und unteren Teil vertauschen",
	del:"Ausgewählte Atome und Bindungen löschen",
	rotate:"Auswahl drehen",
	"3d_rotate":"Auswahl im Raum drehen",
	bond_rotate:"Auswahl um Bindung drehen",
	newAtomSym:"Atomsorte oder Kürzel für eine Vorlage",
	atom:"Atome ersetzen",
	single:"Einfachbindungen zeichnen",
	"double":"Doppelbindungen zeichnen",
	triple:"Dreifachbindungen zeichnen",
	singleUp:"Einfachbindungen aus der Ebene herauszeichnen",
	singleDown:"Einfachbindungen in die Ebene hineinzeichnen",
	singleEither:"Einfachbindungen mit undefinierter Stereochemie zeichnen",
	anyBond:"Nicht spezifizierte Bindung",
	aromaticBond:"Aromatische Bindung",
	drawChain:"Ketten zeichnen",
	createGroupButton:"Gruppe aus Auswahl erstellen",
	ungroupButton:"Gruppierungen entfernen",
	clean2D:"2D-Strukturoptimierung",
	clean3D:"3D-Strukturoptimierung",
	setHotspot:"Anknüpfungspunkt der Vorlage setzen",
	plusButton:"Reaktionskomponenten durch ein Plus trennen",
	arrowButton:"Reaktionspfeil"
};